BEGIN;

-- справочники 

CREATE TABLE roles (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_title text NOT NULL UNIQUE
);

CREATE TABLE visibilities (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL UNIQUE
);

CREATE TABLE status (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL UNIQUE
);

CREATE TABLE actions (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL UNIQUE
);

-- пользователи

CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL UNIQUE,
  nickname      text NOT NULL,
  password_hash text NOT NULL,
  role_id       integer NOT NULL REFERENCES roles(id) ON UPDATE CASCADE
);

-- основные сущности 

CREATE TABLE tracks (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  file_name text NOT NULL,
  file_path text NOT NULL,
  duration  integer NOT NULL CHECK (duration >= 0)
);

CREATE TABLE course (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  visibility_id   integer NOT NULL REFERENCES visibilities(id) ON UPDATE CASCADE,
  title           text NOT NULL,
  description     text,
  cover_image_path text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE task (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id    integer NOT NULL REFERENCES tracks(id) ON UPDATE CASCADE ON DELETE CASCADE,
  status_id   integer NOT NULL REFERENCES status(id) ON UPDATE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  started_at  timestamptz,
  finished_at timestamptz,
  CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE tablatures (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id        integer NOT NULL REFERENCES task(id) ON UPDATE CASCADE ON DELETE CASCADE,
  visibility_id  integer NOT NULL REFERENCES visibilities(id) ON UPDATE CASCADE,
  json_format    json NOT NULL,
  result_path    text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- реакции/комментарии 

CREATE TABLE course_reactions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id     integer NOT NULL REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  reaction_type text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  -- чтобы один пользователь не ставил одну и ту же реакцию много раз (можешь убрать/изменить)
  UNIQUE (course_id, user_id, reaction_type)
);

CREATE TABLE course_comments (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  course_id  integer NOT NULL REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
  content    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tablature_reactions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tablature_id  integer NOT NULL REFERENCES tablatures(id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  reaction_type text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tablature_id, user_id, reaction_type)
);

CREATE TABLE tablature_comments (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  tablature_id integer NOT NULL REFERENCES tablatures(id) ON UPDATE CASCADE ON DELETE CASCADE,
  content      text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- статистика =====

CREATE TABLE statistics (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  action_id  integer NOT NULL REFERENCES actions(id) ON UPDATE CASCADE,
  course_id  integer NOT NULL REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- индексы под частые связи 

CREATE INDEX idx_users_role_id              ON users(role_id);
CREATE INDEX idx_tracks_user_id             ON tracks(user_id);
CREATE INDEX idx_course_user_id             ON course(user_id);
CREATE INDEX idx_course_visibility_id       ON course(visibility_id);

CREATE INDEX idx_task_track_id              ON task(track_id);
CREATE INDEX idx_task_status_id             ON task(status_id);

CREATE INDEX idx_tablatures_task_id          ON tablatures(task_id);
CREATE INDEX idx_tablatures_visibility_id    ON tablatures(visibility_id);

CREATE INDEX idx_course_reactions_course_id  ON course_reactions(course_id);
CREATE INDEX idx_course_reactions_user_id    ON course_reactions(user_id);

CREATE INDEX idx_course_comments_course_id   ON course_comments(course_id);
CREATE INDEX idx_course_comments_user_id     ON course_comments(user_id);

CREATE INDEX idx_tabl_reactions_tabl_id      ON tablature_reactions(tablature_id);
CREATE INDEX idx_tabl_reactions_user_id      ON tablature_reactions(user_id);

CREATE INDEX idx_tabl_comments_tabl_id       ON tablature_comments(tablature_id);
CREATE INDEX idx_tabl_comments_user_id       ON tablature_comments(user_id);

CREATE INDEX idx_statistics_user_id          ON statistics(user_id);
CREATE INDEX idx_statistics_course_id        ON statistics(course_id);
CREATE INDEX idx_statistics_action_id        ON statistics(action_id);

COMMIT;
