"""add course lessons

Revision ID: 0004_add_course_lessons
Revises: 0003_add_course_tags
Create Date: 2026-03-12
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0004_add_course_lessons"
down_revision = "0003_add_course_tags"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS course_lessons (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id integer NOT NULL REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
                title text NOT NULL,
                content text NOT NULL DEFAULT '',
                position integer NOT NULL DEFAULT 1 CHECK (position >= 1),
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
    )
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_course_lessons_course_id ON course_lessons(course_id)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_course_lessons_position ON course_lessons(course_id, position, id)"))


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS idx_course_lessons_position"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_course_lessons_course_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS course_lessons"))
