"""add user lesson progress

Revision ID: 0005_add_user_lesson_progress
Revises: 0004_add_course_lessons
Create Date: 2026-03-12
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0005_add_user_lesson_progress"
down_revision = "0004_add_course_lessons"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS user_lesson_progress (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
                lesson_id integer NOT NULL REFERENCES course_lessons(id) ON UPDATE CASCADE ON DELETE CASCADE,
                is_completed boolean NOT NULL DEFAULT false,
                completed_at timestamptz,
                updated_at timestamptz NOT NULL DEFAULT now(),
                UNIQUE(user_id, lesson_id)
            )
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS idx_user_lesson_progress_user_id ON user_lesson_progress(user_id)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS idx_user_lesson_progress_lesson_id ON user_lesson_progress(lesson_id)"
        )
    )


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_lesson_progress_lesson_id"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_lesson_progress_user_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS user_lesson_progress"))
