"""add author role requests

Revision ID: 0006_add_author_role_requests
Revises: 0005_add_user_lesson_progress
Create Date: 2026-03-13
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0006_add_author_role_requests"
down_revision = "0005_add_user_lesson_progress"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS author_role_requests (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
                message text NOT NULL,
                status text NOT NULL DEFAULT 'pending',
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS idx_author_role_requests_user_id ON author_role_requests(user_id)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS idx_author_role_requests_status ON author_role_requests(status)"
        )
    )
    op.execute(
        sa.text(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_author_role_requests_user_pending
            ON author_role_requests(user_id)
            WHERE lower(status) = 'pending'
            """
        )
    )


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS uq_author_role_requests_user_pending"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_author_role_requests_status"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_author_role_requests_user_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS author_role_requests"))
